# Generated by Django 5.1.1 on 2024-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="restaurant",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("owner", "Owner"),
                    ("employee", "Employee"),
                    ("customer", "Customer"),
                ],
                max_length=20,
            ),
        ),
    ]
